 /* Using the Spotify API (https://developer.spotify.com/) song recommendations are generated by genre
    genre is matched to a corresponding mood.
    Notes:
    - to use the Spotify API, in the header for the request, an OUATH token
      from the users account is required; i did not want to have to sign in
      to my Spotify account each time the app reloads. As well, since this is a
      personal project, the functionality of a sign in screen, wasn't
      necesary for my purposes. Thus a SPOTIFY OAUTH TOKEN IS REQUIRED TO USE THIS ROUTER
*/

const express = require('express');
const bodyParser = require('body-parser');
const cors = require("cors");
const fetch   = require('node-fetch');

const { musicGenre } = require('./helper_modules/musicGenre');

//INSERT YOUR SPOTIFY OAUTH TOKEN HERE
const OAUTH_TOKEN = "";
const URL = "https://api.spotify.com/v1/recommendations?limit=1&market=US&seed_genres=";


let musicRouter = express.Router();

musicRouter.use(bodyParser.json());
musicRouter.use(cors());


musicRouter.get('/:mood', (req, res, next) => {
    //takes the mood from the parameters recieved
    const mood = req.params.mood;
    //matches mood to a genre table
    const genre = findGenre(mood);
    
    const endpoint = URL + genre;
    fetch(endpoint, {
        method: 'GET',
        headers: {
            'Accept': "application/json",
            'Content-Type': "application/json",
            'Authorization': `Bearer ${OAUTH_TOKEN}`
        }
    })
        
    .then(response => {
        if(response.ok){
            //of the response was recieved okay, convert to json 
            return response.json();
        } 
        throw new Error('Request failed!');
    }, networkError => {
        console.log(networkError.message);
    })
    .then(jsonResponse => {
        //return the json response back to script.js for handling
        res.send(JSON.stringify(jsonResponse));
    })

});


//function that matches mood to a genre
function findGenre(mood){
    //the mood parameter has unnecessary characters
    mood = mood.replace(':','');
    return musicGenre(mood);
}


module.exports = musicRouter;